### ISSUE TITLE
[Integrate] As a logged-in user, I can submit my answers to the survey questions

### ISSUE THREAD

**Issue by Thieurom** [nimblehq/flutter-ic-kaung-thieu#30]
## Why
The user can submit their answers to the survey questions.

## Acceptance Criteria
- The API endpoint `/api/v1/responses` is called.
  - If the API returns success, show the Complete Survey screen. Then after 3 seconds, the app will navigate to the Home screen.
  - If the API returns an error, show an error popup.
- Unit tests are added and passed.

## Design

![Image](https://user-images.githubusercontent.com/17972674/228429888-d547e719-da0b-42f6-aff4-b3793a15ee62.png)

**Comment by manh-t** [comment]
@Thieurom we should return the user to the Home screen when they complete the survey 🙋

**Comment by Thieurom** [comment]
@manh-t I noticed this too when planning the backlog, then I forgot 🙏
Since we have a [accompanied UI task](#29), I'll update the requirement on that!
