### ISSUE TITLE
[Chore] Add UI integration testing - (1/3) Login test

### ISSUE THREAD

**Issue by Thieurom** [nimblehq/flutter-ic-kaung-thieu#33]
### Why
Add UI integration testing to make sure the app's flow works as expected.

## Acceptance Criteria
- Add a flow test case with the following steps:
  - Launch the app.
  - Navigate to the Login screen.
  - Input the Email and Password text fields with valid credentials.
  - Tap the **Log in** button
  - Login successfully, then navigate to the Home screen.

**Comment by manh-t** [comment]
@Thieurom for the UI integration testing, I believe the test cases for this task will be huge, and it can be challenging for us - the reviewer, to review the PR. I would suggest separating the UI integration testing task into three tasks:
- UI integration test - Login test
- UI integration test - Home test
- UI integration test - Taking survey test

**Comment by Thieurom** [comment]
@manh-t Thank you!
I've created 3 separated stories for UI integration tests, including this, #34, and #35.
